#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
